export const DATA_LIST = [
  {
    id: 1,
    name: "John Doe",
    age: 30,
    email: "john.doe@example.com",
    phone: "555-1234",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 25,
    email: "jane.smith@example.com",
    phone: "555-5678",
  },
  {
    id: 3,
    name: "Bob Johnson",
    age: 45,
    email: "bob.johnson@example.com",
    phone: "555-9012",
  },
  {
    id: 4,
    name: "Sue Wilson",
    age: 35,
    email: "sue.wilson@example.com",
    phone: "555-3456",
  },
  {
    id: 5,
    name: "Tom Brown",
    age: 50,
    email: "tom.brown@example.com",
    phone: "555-7890",
  },
  {
    id: 6,
    name: "John Doe",
    age: 30,
    email: "john.doe@example.com",
    phone: "555-1234",
  },
  {
    id: 7,
    name: "Jane Smith",
    age: 25,
    email: "jane.smith@example.com",
    phone: "555-5678",
  },
  {
    id: 8,
    name: "Bob Johnson",
    age: 45,
    email: "bob.johnson@example.com",
    phone: "555-9012",
  },
  {
    id: 9,
    name: "Sue Wilson",
    age: 35,
    email: "sue.wilson@example.com",
    phone: "555-3456",
  },
  {
    id: 10,
    name: "Tom Brown",
    age: 50,
    email: "tom.brown@example.com",
    phone: "555-7890",
  },
  {
    id: 11,
    name: "John Doe",
    age: 30,
    email: "john.doe@example.com",
    phone: "555-1234",
  },
  {
    id: 12,
    name: "Jane Smith",
    age: 25,
    email: "jane.smith@example.com",
    phone: "555-5678",
  },
  {
    id: 13,
    name: "Bob Johnson",
    age: 45,
    email: "bob.johnson@example.com",
    phone: "555-9012",
  },
  {
    id: 14,
    name: "Sue Wilson",
    age: 35,
    email: "sue.wilson@example.com",
    phone: "555-3456",
  },
  {
    id: 15,
    name: "Tom Brown",
    age: 50,
    email: "tom.brown@example.com",
    phone: "555-7890",
  },
];
